### ISSUE TITLE
Using nats Object Store to send binary updates ?

### ISSUE THREAD

**Issue by gedw99** [RaaLabs/steward#12]
Steward is pretty interesting 

You could use nats object Store to send binary updates to ships to update the software running on them too. Maybe it’s already there as I have not had a chance to fully read the spec in the readme

**Comment by gedw99** [comment]
Ah found it ? 

https://github.com/RaaLabs/steward#reqcopysrc

**Comment by postmannen** [comment]
Thanks :)

Yes, the REQCopySrc is what is being used for that today, but I was not aware of the Nats Object Store, and it is definitely a thing I will check out more. Thanks a lot for the tip :)

**Comment by gedw99** [comment]
Am going to try this out this weekend.

one thing that makes it a bit slower is that there are no dummy examples. Even just a few simple binaries built in golang that the steward system can call would be useful.

**Comment by postmannen** [comment]
There are some general examples for all the request methods in the Readme, but there are more examples in the [`doc`](https://github.com/RaaLabs/steward/tree/main/doc/example-messages) folder.
Have a plan about adding more examples soon.

**Comment by postmannen** [comment]
About what binaries you can call.. If I understand you right..you can call anything that you can call via f.ex. bash. So as long as a binary is present on the node you send the message to it will be executed.
You can also run a full bash script as a message if you want to, or f.ex. python or other as long as it is installed on the node that you're sending the message to. Check out the 'k3s-' examples under the doc/example folder for an example of how you can install a k3s kubernetes node, deploy some containers, then delete it all again with 3 messages.

**Comment by gedw99** [comment]
thanks.  I see your point.

you mean these right ?

https://github.com/RaaLabs/steward/tree/main/doc/example-messages

**Comment by gedw99** [comment]
btw these messages are encoded using CBOR ? 
I ask because Schema Evolution is so important with distributed messaging.

**Comment by postmannen** [comment]
Yes, CBOR or GOB. You specify which you want by setting flag at startup, or changing the config file.
GOB is the default, but CBOR is to prefer. The reason GOB is the default is that it was the first one that was implemented, and I needed backwards compatibility.

But one thing which is nice to know is that both serialization format and compression is for publishing messages. All Steward nodes can receive both GOB and CBOR, and compressed/not-compressed messages and will decode it as needed for all different options.
