### ISSUE TITLE
Goals of this project/Consider studying Salt's architecture

### ISSUE THREAD

**Issue by dontlaugh** [RaaLabs/steward#2]
We discussed this in Slack briefly, but this project is similar to the early days of Salt, which started out as very limited remote execution. Over time, it accumulated tons of code and features.

I think the core Salt architecture and DSL are solid. But the implementation is a mess. It's a metric ton of Python. There are more open issues on Salt than the Kubernetes project. Even a casual user of Salt is guaranteed to find bugs.

Still, I am experienced with it. And, right now, I need the feature set and extensibility of Salt.

For the month of April, Pluralsight (which is worth paying for anyway, imo) is free. This course will give you a good overview that the docs (which are also a mess) cannot. https://app.pluralsight.com/paths/skills/implementing-it-automation-with-salt-open

If you intend to reach into the higher-level config management space, it is worth it to linger on the design, and learn from the mistakes of the past.

**Comment by postmannen** [comment]
Indeed, and thanks a lot for the tips.

The plan is to only implements the basic's of what is needed for management like run a shell, tail files, write files, http get, and possibly general IO in the form of raw UDP or TCP streams. But I have not decided on the last IO part there yet, and I'm not sure if it makes sense at all. 
To add some context for the IO part , the initial idea was to be able to transfer packets from IOT devices. But the more I think about it the more I'm leaning towards just keeping the methods mentioned earlier, and rather use for example CLI command to trigger something else who will read those data's and use the already defined file methods for example to deliver this back to the central. But it's not put on ice.

The reason for this is in most ways exactly to avoid ending up as you describe, and I don't want it to be become a thing that will need constant updates for various plugins. The already defined methods let's you do more or less anything with a host, and those methods haven't changed much over the last decade either. Both Bash file io, and http have been kind of stable over the years.

My idea about this project is that it should be a core service which let's you do most things with a small set of methods, and if you want more functionality like authentication for users, plugins for APT/RPM, and other you build that as a layer above Steward, where it uses the API of Steward to send messages on a subject to one or a set of nodes.
Like TCP/UDP, it knows how to transfer raw TCP and UDP data streams, and the app decoding is at layer 7. TCP and UDP doesn't really care. This is the same way I like to think about what I want Steward to be(come). 

Back to the original topic :) , referencing our talk on slack earlier. I think plugins are out of scope entirely.

Thanks again for the advice :)
